#include <fstream>


/*
	Tool for generating lookup tables
*/

// write a table
void writeTable(std::ofstream &f, int *table, int size) {
	f << "{" << std::endl;
	for (int j = 0; j < size / 16; ++j) {
		f << "\t";
		for (int i = 0; i < 16; ++i) {
			f << table[j * 16 + i] << ", ";
		}
		f << std::endl;
	}
	f << "};" << std::endl;
}

// generate lookup table for I2S interface
void generateI2S(const std::string &path) {
	int table[256];
	for (int j = 0; j < 256; ++j) {
		int entry = 0b100100100100100100100100;

		// set bits
		for (int i = 0; i < 8; ++i) {
			if (j & (1 << i)) {
				entry |= 1 << (i * 3 + 1);
			}
		}

		table[j] = entry;
	}

	std::ofstream f(path);
	f << "// generated by generateI2S()" << std::endl;
	f << "const int32_t bitTable[256] = ";
	writeTable(f, table, 256);
	f.close();
}


int main(int argc, const char **argv) {

	generateI2S("coco/nrf52/coco/platform/bitTable_I2S.hpp");

	return 0;
}
